### ISSUE TITLE
USER STORY: Sign Up

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/moviegeek-booking#1]
EPIC: Authorisation

As a **new user**, I can **sign up with form validation** so that **I can create a new account.**

# **Acceptance Criteria**
- Sign up form contains fields for username, email, password, confirm password
- Form has password rules and validation
- Submitting valid form creates new user account
- Message is displayed to give visual feedback to the user

# **Tasks**
- [x] Use Django User model
- [x] Add form field validation
- [x] Create user on valid submission
- [x] Add message confirmation
- [x] Add template and styling
