### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/moviegeek-booking#10]
As a **user** I can **view information about movies** so that **I can choose movie to book tickets to.**

# **Acceptance Criteria**
- Homepage displays movie list with information about each movie
- Trailer and booking buttons

# **Tasks**
- [x] Displays movie details
- [x] Link buttons to trailer and booking
- [x] Add template and styling
