### ISSUE TITLE
USER STORY: Update/Delete Profile

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/moviegeek-booking#12]
EPIC: User Profile

As a **role** I can **capability** so that **received benefit**

# **Acceptance Criteria**
- Form allows changing details in the profile
- Users can enter and save new profile information for all relevant fields
- Users can delete their profile
- Message is displayed to give visual feedback to the user

# **Tasks**
- [ ] Profile update view
- [ ] Edit form fields
- [ ] Delete user information from the database if the profile is deleted
- [ ] Add message confirmation
