### ISSUE TITLE
USER STORY: Profile Picture Update/Upload

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/moviegeek-booking#14]
EPIC: User Profile

As a **user** I can **upload and update my profile picture** so that **I can change my account image and make my profile more personalised.**

# **Acceptance Criteria**
- Users can change their profile image
- Displays updated image
- Users can upload images
- Images are stored and retrieved successfully using Cloudinary
- Message is displayed to give visual feedback to the user

# **Tasks**
- [ ] Add edit profile picture view
- [ ] Image upload field in form
- [ ] Handle image upload and save
- [ ] Update image in User model
- [ ] Display updated image
- [ ] ImageField on User model
- [ ] Add message confirmation
