### ISSUE TITLE
USER STORY: Log Out

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/moviegeek-booking#15]
EPIC: Authorisation

As a **a logged in user** I can **log out** so that **I can securely end my session.**

# **Acceptance Criteria**
- Logout button/link logs user out
- Redirects to homepage
- User session ended
- Message is displayed to give visual feedback to the user

# **Tasks**
- [x] Add logout link to templates
- [x] Redirect to main page
- [x] End user session
- [x] Add message confirmation
