### ISSUE TITLE
USER STORY: Verify Email

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/moviegeek-booking#3]
As a **new user** I can **verify and confirm my email address** so that **I can complete account registration.**

# **Acceptance Criteria**
- New users are sent verification email
- Clicking verify link opens a new page and enables user to confirm email address
- Confirming email completes account registration
- Message is displayed to give visual feedback to the user

# **Tasks**
- [ ] Generate email verification link
- [ ] Send verification email after signup
- [ ] Allow user to confirm email through link
- [ ] Add template and styling
- [ ] Add message confirmation
