### ISSUE TITLE
USER STORY:  Password Reset

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/moviegeek-booking#5]
As a **user** I can **reset my password by entering my email** so that **I can recover access if forgotten.**

# **Acceptance Criteria**
- Password reset page contains email input
- Submitting email sends reset link
- Confirmation that the link is sent is present
- Message is displayed to give visual feedback to the user
- Clicking on reset link allows user to create new password

# **Tasks**
- [x] Use password reset template and add styling
- [x] Allow email input
- [x] Send email reset link to user
- [x] Add message confirmation
- [x] Allow password change
