### ISSUE TITLE
USER STORY: Edit/Delete booking

### ISSUE THREAD

**Issue by nataliiasolomchak21** [nataliiasolomchak21/moviegeek-booking#8]
EPIC: Booking

As a **user** I can **edit or delete my existing bookings on my profile** so that **I can manage my tickets.**

# **Acceptance Criteria**
- Each booking on profile has edit and delete buttons
- Editing booking allows user to change details
- Deleting booking removes it from profile
- Message is displayed to give visual feedback to the user

# **Tasks**
- [x] Add edit view
- [x] Update Booking model on submit
- [x] Delete view deletes booking
- [x] Redirect to updated profile
- [x] Add message confirmation
